---

nodejs_nvm_ver: "0.29.0"
nodejs_nvm_install_url: "https://raw.githubusercontent.com/creationix/nvm/v{{nodejs_nvm_ver}}/install.sh"
nodejs_nvm_install_script: "{{home_dir}}/tmp/install.sh"
nodejs_default_ver: "6.9"
nodejs_versions:
  - "6.9"
nodejs_versions_to_remove:
  - "0.10.43"
  - "0.12.12"
  - "0.10.44"
  - "0.10.45"
  - "0.10.46"
  - "0.10.47"
  - "0.10.48"
  - "0.12.13"
  - "0.12.14"
  - "0.12.15"
  - "0.12.16"
  - "0.12.17"
  - "0.12.18"
  - "4.6.2"
  - "4.2.4"
  - "5.9.1"
  - "5.10.1"
  - "5.12.0"
  - "6.5.0"
nodejs_npm_packages:
  - babel
  - babel-eslint
  - coffee
  - coffeelint
  - cult
  - eslint
  - eslint-config-airbnb
  - eslint-plugin-import
  - eslint-plugin-jsx-a11y
  - eslint-plugin-react
  - eslint-plugin-flowtype
  - grunt
  - grunt-cli
  - gulp
  - nsp
  - sass-lint
  - yo
nodejs_elm_packages:
  - elm
  - elm-format
  - elm-oracle
  - elm-test
