---

brew_install_cmd: "ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
brew_bin: "/usr/local/bin/brew"
brew_cask_bin: "/usr/local/bin/brew-cask"
brew_base_packages:
  - name: autoconf
  - name: automake
  - name: bash
  - name: bash-completion
  - name: bat
  - name: bazaar
  - name: certbot
  - name: cmake
  - name: coreutils
  - name: cscope
  - name: ctags
  - name: curl
  - name: direnv
  - name: exercism
  - name: findutils
  - name: fn
  - name: fontconfig
  - name: freetype
  - name: fswatch
  - name: fzf
  - name: gettext
  - name: git
  - name: git-duet
  - name: git-extras
  - name: git-lfs
  - name: git-secrets
  - name: goenv
  - name: gnu-sed
  - name: gnu-tar
  - name: graphviz
  - name: hadolint
  - name: heroku
  - name: hub
  - name: jq
  - name: kubectl
  - name: libevent
  - name: libffi
  - name: libidn
  - name: libmemcached
  - name: libmpc
  - name: libpng
  - name: libxml2
  - name: libyaml
  - name: lorem
  - name: lua
  - name: luajit
  - name: makedepend
  - name: memcached
  - name: mercurial
  - name: moreutils
  - name: nomad
  - name: opam
  - name: packer
  - name: protobuf
  - name: readline
  - name: ripgrep
  - name: s3cmd
  - name: snappy
  - name: sqlite
  - name: terraform
  - name: thefuck
  - name: the_silver_searcher
  - name: tmate
  - name: tree
  - name: vault
  - name: watchman
  - name: wget
  - name: xhyve
  - name: yarn
brew_cask_applications:
  - name: alfred
  - name: appzapper
  - name: arduino
  - name: atom
  - name: bartender
  - name: caffeine
  - name: firefox
  - name: flux
  - name: google-chrome
  - name: google-cloud-sdk
  - name: google-hangouts
  # TODO: Requires password, become sudo
  - name: gpg-suite
  - name: harvest
  - name: imagealpha
  - name: imageoptim
  - name: insomniax
  - name: istat-menus
  - name: iterm2
  - name: keybase
  - name: little-snitch
  - name: minikube
  - name: nordvpn
  - name: spotify
  - name: sublime-text
  - name: the-unarchiver
  - name: time-out
  - name: tor-browser
  - name: tunnelblick
  - name: vagrant
  - name: virtualbox
  - name: viscosity
  - name: vmware-fusion
  - name: vlc
  - name: whatsapp
  - name: youll-never-take-me-alive
brew_taps:
  - name: git-duet/tap
  - name: homebrew/cask-versions
  - name: heroku/brew
