---

gopath_dir: "{{ workspace_dir }}/go"
golang_default_packages:
  # Golang tools
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/tools/cmd/cover
  - golang.org/x/tools/cmd/godoc
  - golang.org/x/tools/cmd/gorename
  - golang.org/x/tools/cmd/guru

  # Common packages
  - github.com/derekparker/delve/cmd/dlv
  - github.com/golang/lint/golint
  - github.com/mitchellh/gox
  - github.com/smartystreets/goconvey
  - github.com/pengwynn/flint
  - github.com/fatih/hclfmt
  - github.com/rakyll/hey
  - github.com/github/hub
  - github.com/mvdan/unparam
  - github.com/davecheney/httpstat
  - github.com/stretchr/testify
  - github.com/sqs/goreturns
  - github.com/zmb3/gogetdoc

  # vim-go dependencies
  - github.com/nsf/gocode
  - github.com/alecthomas/gometalinter
  - github.com/rogpeppe/godef
  - github.com/kisielk/errcheck
  - github.com/jstemmer/gotags
  - github.com/klauspost/asmfmt/cmd/asmfmt
  - github.com/fatih/motion

  # AWS dependencies
  - github.com/fujiwara/kinesis-tailf/cmd/kinesis-tailf
  - github.com/mtchavez/aws-mfa-sts
